# Site settings
title: Devp-YG | Mobile Apps
email: devp.yg@gmail.com
description: >-
  Devp-YG develops practical mobile apps for everyday movement and life.
lang: ko
timezone: Asia/Seoul
baseurl: ""
url: "https://devp-yg.github.io"
twitter_username: ""
github_username: devp-yg
copyrights_year: 2020

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

exclude:
  - _archive
  - .idea
  - .jekyll-cache
  - README.md
  - LICENSE
