# Site settings
title: Developer's YG
email: devp.yg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a page for devp-yg.
  Devp-yg develops the mobile application on iOS and AndroidOS.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" #"http://locahost:4000" # the base hostname & protocol for your site
twitter_username: ""
github_username:  devp-yg
copyrights_year: 2023

# Build settings
markdown: kramdown
